### ISSUE TITLE
compiling error gelf.h

### ISSUE THREAD

**Issue by prashants** [ktap/ktap#34]
make[1]: Leaving directory `/home/prashants/kernel/v3.12-rc1'
cc  -Wall -O2 -o userspace/lex.o -c userspace/lex.c
cc  -Wall -O2 -o userspace/parser.o -c userspace/parser.c
cc  -Wall -O2 -o userspace/code.o -c userspace/code.c
cc  -Wall -O2 -o userspace/dump.o -c userspace/dump.c
cc  -Wall -O2 -o userspace/main.o -c userspace/main.c
cc  -Wall -O2 -o userspace/util.o -c userspace/util.c
cc  -Wall -O2 -o userspace/ktapio.o -c userspace/ktapio.c
cc  -Wall -O2 -o userspace/eventdef.o -c userspace/eventdef.c
In file included from userspace/eventdef.c:32:0:
userspace/symbol.h:22:18: fatal error: gelf.h: No such file or directory
compilation terminated.
make: **\* [userspace/eventdef.o] Error 1

$uname -a
Linux mintlinux 3.12.0-rc1-custom0909 #1 SMP Thu Sep 19 19:30:07 IST 2013 x86_64 GNU/Linux

**Comment by IonicaBizau** [comment]
@prashants Thanks! Worked for me building Facebook Flow tool. :smile:

**Comment by maryamEbrahimzadeh** [comment]
how did you install libelf-dev ?
